/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by Builder.io.
 */

"use client"

import * as React from "react";
import "../Navbar/navbar-style.css";

const Nav = ({ UploadDesktopLogo, UploadMobileLogo, NavColumns, NavIcons }) => {

  return (
  <div className="nav-container parent">
        <div className="navbar" id="main-navbar">
            {UploadDesktopLogo ? (
              <div className="Nav-Logo desktop-view">
                  <a href="/">
                    <img
                      src={UploadDesktopLogo}
                      alt="Main Logo"
                    />
                  </a>
              </div>
              ) : (
              <p>No Decktop Logo Available</p>
            )}
            
            <div className="navbar" id="mobile-logo">
              {UploadMobileLogo ? (
                <div className="Nav-Logo">
                    <a href="/">
                      <img
                        src={UploadMobileLogo}
                        alt="Main Logo"
                      />
                    </a>
                </div>
                ) : (
                <p>No Mobile Logo Available</p>
              )}
            </div>

            <div className="navbar" id="hamburger-menu">
              &#9776;
            </div>
        </div>

        {NavColumns && NavColumns.length > 0 ? (
            <div className="navbar two" id="navbar-middle">
                {NavColumns.map((navlist, index) => (
                  <a key={index} href={navlist.NavUrl}>
                    {navlist.NavItem}
                  </a>
                ))}
            </div>
              ) : (
            <p>No Nav Listing Available</p>
          )}

          <div className="navbar three" id="last-navbar">
              {NavIcons && NavIcons.length > 0 ? (
                  <ul>
                    {NavIcons.map((item, icon, index) => (
                      <li key={index}>
                        {NavIcons ? (
                          <a href={item.IconUrl}>{item.PageTitle}</a>
                            ) : (
                          <a href={icon.IconUrl}>
                            <img src={icon.Icon} alt="Icon" />
                          </a>
                        )}
                      </li>
                    ))}
                  </ul>
                  ) : (
                <p>No Icons Available</p>
              )}
          </div>
          {/* This is help page  */}
  </div>
  );
}

export default Nav;