/* eslint-disable @next/next/no-img-element */
/**
 * This code was generated by Builder.io.
 */

"use client"

import * as React from "react";
//import Cart from "../eCommerces/Notifications/Cart/cart";
import "../Navbar/navbar-style.css";

function Image({ src, alt }) {
  // eslint-disable-next-line @next/next/no-img-element
  return <img 
      src={src} 
      alt={alt} 
    />;
}

const Nav = ({ navItems, imageData, NavIcons, image }) => {

  return (
  <div className="container">
    <div className="wrapper">
        <div className="main-navbar">
        {imageData && imageData.length > 0 ? (
          <div className="Nav-Logo">
            {imageData && (
              <a href="/">
                <Image
                  src={image.src || imageData.src }
                  alt={imageData.allowedFileTypes}
                />
              </a>
            )}
          </div>
          ) : (
          <p>No Nav Logo Available</p>
        )}
        
        {navItems && navItems.length > 0 ? (
          <div className="Navbar_Listing">
            {navItems && navItems.map((item, index) => (
              <a key={index} href={item.link}>
                {item.text}
              </a>
            ))}
          </div>
          ) : (
          <p>No Nav Listing Available</p>
        )}

          <div className="navbar-last">
              {NavIcons && NavIcons.length > 0 ? (//There no icon it will be 0 but add no icons
                  <ul>
                    {NavIcons.map((icon, index) => (
                      <li key={index}>
                        <img src={icon.Icon} alt="Icon" />
                          <a href={icon.IconUrl}>{/* Additional link for the icon */}</a>
                      </li>
                    ))}
                  </ul>
                  ) : (
                <p>No Icons Available</p>
              )}
            {/* <Cart/> */}
          </div>
            {/* This is help page  */}
      </div>
    </div>
  </div>
  );
}

export default Nav;